export const LOGIN_REQUEST = "LOGIN_REQUEST" as const;
export const LOGIN_SUCCESS = "LOGIN_SUCCESS" as const;
export const LOGIN_FAILURE = "LOGIN_FAILURE" as const;

export const REGISTER_REQUEST = "REGISTER_REQUEST" as const;
export const REGISTER_SUCCESS = "REGISTER_SUCCESS" as const;
export const REGISTER_FAILURE = "REGISTER_FAILURE" as const;

export const EMAIL_VERIFIED_REQUEST = "EMAIL_VERIFIED_REQUEST" as const;
export const EMAIL_VERIFIED_SUCCESS = "EMAIL_VERIFIED_SUCCESS" as const;
export const EMAIL_VERIFIED_FAILURE = "EMAIL_VERIFIED_FAILURE" as const;

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST" as const;
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS" as const;
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE" as const;
